### ISSUE TITLE
ask_for_values

### ISSUE THREAD

**Issue by arsenovic** [python-ivi/python-vxi11#6]
the pyvisa project used to have a function called [`ask_for_values`](https://pyvisa.readthedocs.org/en/1.5-docs/instruments.html?highlight=ask_for_values#Instrument.ask_for_values) , which believe has recently been [renamed and re-written](https://pyvisa.readthedocs.org/en/master/migrating.html#ask-vs-query) to `query_values`. essentially it was an `ask`, with delimiter splitting and casting, that was ideal for reading arrays.
 

in either case, this function is very useful, and was wondering if a similar thing could implemented in python-vxi11 or python-ivi (which ever is more appropriate). id be happy to do this

**Comment by alexforencich** [comment]
Not a bad idea.  I think most of the high-level read and write calls are done in python-ivi so that they will apply to all of the backends (vxi11, usbtmc, serial, linux-gpib, pyvisa), so that is probably the best place to put them.  See _read_ieee_block and _write_ieee_block near the bottom of ivi.py.

**Comment by arsenovic** [comment]
this was implemented in python-ivi/python-ivi 3ea07b11eff1ea3ce23aec154b19b52e8b2a1706
